### ISSUE TITLE
Suggestion: Rename?

### ISSUE THREAD

**Issue by HilariousCow** [marcin-se/unity_array#1]
Hi there. "Array" is already a type-name in C#, so adding this into unity caused a compile error elsewhere. I think you could either add a namespace so that it can be disambiguated from System.Array, or just rename the class to something like "ArrayOfObjects".

**Comment by marcin-se** [comment]
Good catch, i changed the name to 'Duplicate special'. Thanks!

**Comment by marcin-se** [comment]
Hi Aubrey.

Good catch. Thanks for noticing that and letting me know. Fix applied. I
renamed the script to 'Duplicate special' as i find it a bit more accurate
in the context of Unity.

Thanks,
Marcin

2016-10-25 16:25 GMT+02:00 Aubrey Hesselgren <notifications@github.com>:
